---
name: Lint GitHub Action Workflows

"on":
  push:
    branches:
        - main

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - name: Lint GitHub Action Workflows
        uses: eifinger/actionlint-action@v1
