---
name: Reproduce rye 0.21.0 pip not found error

"on":
    push:
        branches:
            - main

jobs:
    rye:
        runs-on: ubuntu-latest
        steps:
            - run: curl -sSf https://rye-up.com/get | RYE_INSTALL_OPTION="--yes" bash
            - run: source "$HOME/.rye/env" && rye init my-project
            - run: cd my-project && source "$HOME/.rye/env" && rye add black && rye sync
    
    