on:
  workflow_dispatch:


jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    container: alpine
    steps:
      - run: apk add curl python3
      - run: curl -LsSf https://astral.sh/uv/install.sh | sh
      - run: source $HOME/.local/bin/env
      - run: uv init test
