---
name: Test boolean inputs

"on":
  workflow_call:
    inputs:
      booleanInput:
        description: "Just a boolean input"
        type: boolean
        required: false
        default: false
  workflow_dispatch:
    inputs:
      booleanInput:
        description: "Just a boolean input"
        type: boolean
        required: false
        default: false

jobs:
  echo-input:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "booleanInput: ${{ inputs.booleanInput }}"
      - if: ${{ inputs.booleanInput }}
        run: |
          echo "Only executed when true"