---
name: This calls

"on":
  push:
    branches:
      - main

jobs:
  call-other-workflow:
    uses: eifinger/actionlint-playground/.github/workflows/this-gets-called.yml@main
    with:
      missingInput: "This should be caught by actionlint"
